source 'https://rubygems.org'

gem 'rails' ,'1.2.3'

gem 'mysql', '2.8.1'

gem 'daemons', '1.1.8'
gem 'mongrel', '1.1.5'

# rake (0.8.7) uninstalling 0.9.2.2
gem 'rake', '0.8.7'

gem 'gruff', '0.3.7'
gem 'rmagick', '2.13.1'

gem 'memcache-client'
gem 'timecop', '0.3.5'
gem 'system_timer', '1.2.4'

gem 'rubygems-update', '1.3.7'
gem 'bundler', '1.0.21'

gem 'highline', '1.6.1'
gem 'net-ssh', '2.2.2'
gem 'capistrano', '2.9.0'
gem 'capistrano-ext'
gem 'capistrano_colors'

gem 'redgreen'
gem 'rak'
gem 'rcov'

gem 'msgpack', '0.4.5'

gem 'fakeweb'
